version: 1.0.3.{build}
image: Visual Studio 2017
before_build:
  - git clone -q --branch=master https://github.com/Amebis/eduJSON.git ..\eduJSON
  - nuget restore
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: eduOAuth.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)\eduOAuth.dll
  - path: bin\$(configuration)\$(platform)\eduOAuth.pdb
  - path: bin\$(configuration)\$(platform)\sl\eduOAuth.resources.dll
