version: 1.14.{build}
image: Visual Studio 2022
before_build:
  - git clone -q --branch=master https://github.com/Amebis/eduEx.git ..\eduEx
  - git clone -q --branch=master https://github.com/Amebis/eduJSON.git ..\eduJSON
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - Any CPU
  - x86
  - x64
  - ARM64
build:
  project: eduOAuth.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
